
server.http2.enabled: true
spring.application.name: kp-grpc-otel-server
spring.datasource.type: com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.name: hikariPool
management:
  tracing:
    sampling:
      probability: 1.0
logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
#logging.pattern.level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p
#logging.pattern.level: "%5p [${spring.application.name:},%X{trace_id:-},%X{span_id:-}]"
